# Generated by Django 5.2.7 on 2026-04-07 12:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProviderCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('DEYE', 'Deye Cloud'), ('SOLARMAN', 'Solarman')], help_text='Cloud API provider (DEYE or SOLARMAN).', max_length=20, unique=True)),
                ('base_url', models.URLField(help_text='Base URL for API calls (region-specific for Deye).')),
                ('cached_token', models.TextField(blank=True, default='', help_text='Cached access token from the provider API.')),
                ('token_expires_at', models.DateTimeField(blank=True, help_text='When the cached token expires.', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Disable to stop syncing from this provider without deleting.')),
                ('last_used_at', models.DateTimeField(blank=True, help_text='Timestamp of the last successful API call.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Provider Credential',
                'verbose_name_plural': 'Provider Credentials',
            },
        ),
        migrations.CreateModel(
            name='SyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('SUCCESS', 'Success'), ('PARTIAL', 'Partial Success'), ('FAILED', 'Failed')], default='SUCCESS', max_length=10)),
                ('devices_synced', models.PositiveIntegerField(default=0)),
                ('devices_failed', models.PositiveIntegerField(default=0)),
                ('error_message', models.TextField(blank=True, default='')),
                ('credential', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_logs', to='integrations.providercredential')),
            ],
            options={
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['credential', '-started_at'], name='integration_credent_48d62c_idx')],
            },
        ),
    ]
