# Generated by Django 5.2.7 on 2026-04-02 07:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=255, unique=True)),
                ('device_type', models.CharField(choices=[('INVERTER', 'Hybrid Inverter'), ('LOGGER', 'Data logger')], max_length=20)),
                ('auth_token', models.CharField(max_length=64, unique=True)),
                ('status', models.CharField(choices=[('ONLINE', 'Online'), ('OFFLINE', 'Offline')], default='OFFLINE', max_length=20)),
                ('installed_at', models.DateTimeField(blank=True, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='organizations.organization')),
            ],
        ),
    ]
