# Generated by Django 5.2.7 on 2026-04-07 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='data_source',
            field=models.CharField(choices=[('DEYE', 'Deye Cloud'), ('SOLARMAN', 'Solarman'), ('MANUAL', 'Manual / Local')], default='MANUAL', help_text='Which cloud API provides telemetry for this device.', max_length=20),
        ),
        migrations.AddField(
            model_name='device',
            name='last_synced_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp of the last successful telemetry sync.', null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='provider_device_id',
            field=models.CharField(blank=True, default='', help_text='External device ID from the provider API.', max_length=255),
        ),
        migrations.AddField(
            model_name='device',
            name='provider_station_id',
            field=models.CharField(blank=True, default='', help_text='External station/plant ID from the provider API.', max_length=255),
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['data_source', 'status'], name='devices_dev_data_so_ed2f6f_idx'),
        ),
    ]
