# Generated by Django 5.2.7 on 2026-04-07 12:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0002_device_data_source_device_last_synced_at_and_more'),
        ('telemetry', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('DEYE', 'Deye Cloud'), ('SOLARMAN', 'Solarman')], max_length=20)),
                ('alert_code', models.CharField(help_text='Provider-specific alert/error code.', max_length=100)),
                ('alert_name', models.CharField(help_text='Human-readable alert name.', max_length=255)),
                ('severity', models.CharField(choices=[('INFO', 'Info'), ('WARNING', 'Warning'), ('CRITICAL', 'Critical')], default='WARNING', max_length=20)),
                ('occurred_at', models.DateTimeField(help_text='When the alert was triggered.')),
                ('resolved_at', models.DateTimeField(blank=True, help_text='When the alert was resolved (null = still active).', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this alert is currently active.')),
                ('notification_sent', models.BooleanField(default=False, help_text='Whether a push notification was sent for this alert.')),
                ('raw_data', models.JSONField(blank=True, default=dict, help_text='Full alert payload from provider API.')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='devices.device')),
            ],
            options={
                'ordering': ['-occurred_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('ALERT', 'Device Alert'), ('DEVICE_OFFLINE', 'Device Offline'), ('SYNC_FAILURE', 'Sync Failure')], max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('recipient_user_id', models.IntegerField(help_text='User ID who received this notification.')),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('delivered', models.BooleanField(default=False)),
                ('fcm_message_id', models.CharField(blank=True, default='', help_text='Firebase Cloud Messaging message ID.', max_length=255)),
                ('alert', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='telemetry.devicealert')),
            ],
            options={
                'ordering': ['-sent_at'],
            },
        ),
        migrations.CreateModel(
            name='TelemetryReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True, help_text='When this reading was captured (UTC).')),
                ('source', models.CharField(choices=[('DEYE', 'Deye Cloud'), ('SOLARMAN', 'Solarman'), ('MANUAL', 'Manual / Local')], default='MANUAL', help_text='Which provider this reading came from.', max_length=20)),
                ('power_w', models.FloatField(blank=True, help_text='Total active output power in Watts.', null=True)),
                ('energy_today_kwh', models.FloatField(blank=True, help_text='Energy generated today in kWh.', null=True)),
                ('energy_total_kwh', models.FloatField(blank=True, help_text='Lifetime energy generated in kWh.', null=True)),
                ('battery_soc', models.FloatField(blank=True, help_text='Battery State of Charge (0-100%).', null=True)),
                ('battery_power_w', models.FloatField(blank=True, help_text='Battery charge/discharge power in Watts (positive=charging).', null=True)),
                ('grid_power_w', models.FloatField(blank=True, help_text='Grid import/export power in Watts (positive=importing).', null=True)),
                ('load_power_w', models.FloatField(blank=True, help_text='Total load consumption in Watts.', null=True)),
                ('pv1_power_w', models.FloatField(blank=True, help_text='PV string 1 power in Watts.', null=True)),
                ('pv2_power_w', models.FloatField(blank=True, help_text='PV string 2 power in Watts.', null=True)),
                ('pv_total_power_w', models.FloatField(blank=True, help_text='Total PV input power in Watts.', null=True)),
                ('voltage_ac', models.FloatField(blank=True, help_text='AC output voltage in Volts.', null=True)),
                ('frequency_hz', models.FloatField(blank=True, help_text='AC output frequency in Hz.', null=True)),
                ('temperature_c', models.FloatField(blank=True, help_text='Inverter temperature in °C.', null=True)),
                ('raw_response', models.JSONField(blank=True, default=dict, help_text='Full API response preserved for debugging.')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telemetry_readings', to='devices.device')),
            ],
            options={
                'db_table': 'telemetry_telemetryreading',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.DeleteModel(
            name='Telemetry',
        ),
        migrations.AddIndex(
            model_name='devicealert',
            index=models.Index(fields=['device', '-occurred_at'], name='telemetry_d_device__cb955e_idx'),
        ),
        migrations.AddIndex(
            model_name='devicealert',
            index=models.Index(fields=['is_active', 'device'], name='telemetry_d_is_acti_71b1d1_idx'),
        ),
        migrations.AddIndex(
            model_name='devicealert',
            index=models.Index(fields=['severity', 'is_active'], name='telemetry_d_severit_a927a9_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationlog',
            index=models.Index(fields=['recipient_user_id', '-sent_at'], name='telemetry_n_recipie_f9eb84_idx'),
        ),
        migrations.AddIndex(
            model_name='telemetryreading',
            index=models.Index(fields=['device', 'timestamp'], name='telemetry_t_device__3a0da3_idx'),
        ),
        migrations.AddIndex(
            model_name='telemetryreading',
            index=models.Index(fields=['device', '-timestamp'], name='telemetry_t_device__da4c8a_idx'),
        ),
        migrations.AddIndex(
            model_name='telemetryreading',
            index=models.Index(fields=['source', 'timestamp'], name='telemetry_t_source_6ac2e4_idx'),
        ),
    ]
